title: Abhinav Handa
description: > # this means to ignore newlines until "baseurl:"
   and I can draw.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Abhinav Handa
tagline: Developer, Explorer and Artist
about-description:  # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: abhihanda23@gmail.com # Add your Email address
phone: +917888735608 # Add your Phone number
website: unknownartist.me # Add your website, do not add http://
linkedin: abhinavhanda
github: abhinavhanda21 # Add your Github handle
twitter: '@abhinavhanda21' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
