title: Abhinav Handa
description: > # this means to ignore newlines until "baseurl:"
  I am a straightforward and amiable person to work within a group. I believe in, never say die attitude, never run away from responsibilities, utilize every second and believe in building relationships. I have a good grasping ability and can understand the facts and situations very comprehensively. I like to work on open source projects,FOSS rocks!!
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Abhinav Handa
tagline: Developer, Explorer and Artist
about-description: I am a straightforward and amiable person to work within a group. I believe in, never say die attitude, never run away from responsibilities, utilize every second and believe in building relationships. I have a good grasping ability and can understand the facts and situations very comprehensively. I like to work on open source projects,FOSS rocks!! # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: abhihanda23@gmail.com # Add your Email address
phone: +917888735608 # Add your Phone number
website: abhinavhanda.me # Add your website, do not add http://
linkedin: abhinavhanda
github: abhinavahanda21 # Add your Github handle
twitter: '@abhinavhanda21' # Add your Twitter handle


# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
